spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      # Static routes - these show in /actuator/gateway/routes
      routes:
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<path>.*), /${path}

        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /${path}

        - id: google-route1
          uri: https://www.google.com
          predicates:
            - Path=/google/**
          filters:
            - RewritePath=/google/(?<remaining>.*), /${remaining}

        # - id: arizona-edu
        #   uri: https://www.arizona.edu/
        #   predicates:
        #     - Path=/arizona/**
        #   filters:
        #     - RewritePath=/arizona/(?<remaining>.*), /${remaining}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
